### ISSUE TITLE
[1.12.2] Crash with newest Thermal Mods

### ISSUE THREAD

**Issue by MasterEnderman** [bonii-xx/MinecraftBitcoin#1]
Crash Report: https://pastebin.com/MBmj2AvX
Forge: 14.23.3.2673
CoFH Core: 4.4.0.10
Thermal Foundation: 2.4.0.14
Thermal Expansion: 5.4.0.20

**Comment by bonii-xx** [comment]
Thanks for the report, I'll take a look. Looks like something in TE changed.
